name: Update README with new weekly logs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/*.md'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual update'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            docs/*.md

      - name: Update README
        if: steps.changed-files.outputs.any_changed == 'true'
        run: node scripts/update_readme.js
